In [52]:
import pandas as pd
import numpy as np

In [53]:
data=pd.read_csv(r"C:\Users\mallikarjun\OneDrive\Documents\marks_csv.csv")
data

    Product   Price        Date
0    Laptop  $56.00  12-06-2025
1     Mouse  $12.00  03-12-2025
2  Keyboard  $16.00  26-08-2025
3   Monitor  $23.00  16-10-2025

In [54]:
data.dtypes

Product    object
Price      object
Date       object
dtype: object

In [55]:
data["Price"] = data["Price"].str.replace("$", "", regex=False).astype(float)
data

    Product  Price        Date
0    Laptop   56.0  12-06-2025
1     Mouse   12.0  03-12-2025
2  Keyboard   16.0  26-08-2025
3   Monitor   23.0  16-10-2025

In [59]:
data["Date"] = pd.to_datetime(data["Date"])
data

    Product  Price       Date
0    Laptop   56.0 2025-12-06
1     Mouse   12.0 2025-03-12
2  Keyboard   16.0        NaT
3   Monitor   23.0        NaT