In [12]:
import pandas as pd
import numpy as np

In [13]:
data=pd.read_csv(r"C:\Users\mallikarjun\OneDrive\Documents\marks_csv.csv")
data

   Student_id    Name   Age Department  Marks
0           1    Abhi  21.0         EC   85.0
1           2   Kiran  22.0        CSE   95.0
2           3   Shivu   NaN         AE    NaN
3           3   Shivu  22.0         AE    NaN
4           4  Deepak  23.0         AI   70.0

In [14]:
data.isna().sum()

Student_id    0
Name          0
Age           1
Department    0
Marks         2
dtype: int64

In [15]:
data["Age"]=data["Age"].fillna(value=data["Age"].median())
data

   Student_id    Name   Age Department  Marks
0           1    Abhi  21.0         EC   85.0
1           2   Kiran  22.0        CSE   95.0
2           3   Shivu  22.0         AE    NaN
3           3   Shivu  22.0         AE    NaN
4           4  Deepak  23.0         AI   70.0

In [16]:
data["Marks"]=data["Marks"].fillna(value=d["Marks"].median())
data

   Student_id    Name   Age Department  Marks
0           1    Abhi  21.0         EC   85.0
1           2   Kiran  22.0        CSE   95.0
2           3   Shivu  22.0         AE   85.0
3           3   Shivu  22.0         AE   85.0
4           4  Deepak  23.0         AI   70.0

In [23]:
data=data.drop_duplicates()
data

   Student_id    Name   Age Department  Marks
0           1    Abhi  21.0         EC   85.0
1           2   Kiran  22.0        CSE   95.0
2           3   Shivu  22.0         AE   85.0
4           4  Deepak  23.0         AI   70.0