In [1]:
import pandas as pd

In [2]:
import numpy as np

In [139]:
datas = pd.read_csv(r"C:\Users\Dell\Downloads\raw\test2.csv")

In [97]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [13]:
datas.isnull()

   Unnamed: 0   Name    Age  Department  Salary
0       False  False  False       False   False
1       False  False  False       False   False
2       False  False  False       False   False
3       False  False   True       False   False
4       False  False  False       False    True
5       False  False  False       False   False

In [15]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [26]:
datas.iloc[1:4,1:4]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [27]:
datas.columns

Index(['Unnamed: 0', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [33]:
datas.rename(columns={"Name":"N","Age":"A","Department":"D","Salary":"S"},inplace=True)

In [34]:
datas

   Unnamed: 0        N     A        D        S
0           0    Alice  25.0       HR  50000.0
1           1      Bob  30.0       IT  60000.0
2           2  Charlie  35.0  Finance  70000.0
3           3    David   NaN       IT  62000.0
4           4      Eve  29.0       HR      NaN
5           5    Alice  25.0       HR  50000.0

In [38]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [55]:
datas.drop('Unnamed: 0',axis=1,inplace=True)

In [56]:
datas

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [57]:
datas["updated_salary"]=datas["Salary"]+5000

In [59]:
datas["updated_salary2"] = datas["Salary"].map(lambda x:x+10000)

In [121]:
datas

   Unnamed: 0     Name   Age Department   Salary Level
0           0    Alice  25.0         HR  50000.0   low
1           1      Bob  30.0         IT  60000.0  High
2           2  Charlie  35.0    Finance  70000.0  High
3           3    David   NaN         IT  62000.0  High
4           4      Eve  29.0         HR      NaN   low
5           5    Alice  25.0         HR  50000.0   low

In [72]:
datas.dropna(inplace=True)

In [73]:
datas.isnull().sum()

Name               0
Age                0
Department         0
Salary             0
updated_salary     0
updated_salary2    0
dtype: int64

In [78]:
datas["Age"] = datas.Age.astype("int")

In [95]:
datas[(datas["Salary"]>50000) | (datas["Salary"] < 65000)]

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
5           5    Alice  25.0         HR  50000.0

In [122]:
datas

   Unnamed: 0     Name   Age Department   Salary Level
0           0    Alice  25.0         HR  50000.0   low
1           1      Bob  30.0         IT  60000.0  High
2           2  Charlie  35.0    Finance  70000.0  High
3           3    David   NaN         IT  62000.0  High
4           4      Eve  29.0         HR      NaN   low
5           5    Alice  25.0         HR  50000.0   low

In [123]:
datas.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
Level         0
dtype: int64

In [133]:
datas["Age"].mean()

np.float64(28.8)

In [136]:
datas["Age"] = datas["Age"].fillna(value=datas["Age"].mean())
datas["Salary"] = datas["Salary"].fillna(value=datas["Salary"].mean())

In [137]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  28.8         IT  62000.0
4           4      Eve  29.0         HR  58400.0
5           5    Alice  25.0         HR  50000.0

In [138]:
datas["Department"].value_counts()

Department
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [140]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [142]:
datas["Age"] = datas["Age"].fillna(method="ffill")
datas["Salary"] = datas["Salary"].fillna(method="bfill")

C:\Users\Dell\AppData\Local\Temp\ipykernel_44816\4191250414.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  datas["Age"] = datas["Age"].fillna(method="ffill")
C:\Users\Dell\AppData\Local\Temp\ipykernel_44816\4191250414.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  datas["Salary"] = datas["Salary"].fillna(method="bfill")

In [144]:
datas.Age.ffill()

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [143]:
datas

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David  35.0         IT  62000.0
4           4      Eve  29.0         HR  50000.0
5           5    Alice  25.0         HR  50000.0

In [145]:
### Column wise apply()
datas["updated_salary"] = datas["Salary"].apply(lambda x:x+500)

In [153]:
## Row wise apply()
datas["level"] =  datas.apply(lambda s:"High" if s["updated_salary"] > 60000 else "Low" ,axis =1 )

In [154]:
datas

   Unnamed: 0     Name   Age Department   Salary  updated_salary level
0           0    Alice  25.0         HR  50000.0         50500.0   Low
1           1      Bob  30.0         IT  60000.0         60500.0  High
2           2  Charlie  35.0    Finance  70000.0         70500.0  High
3           3    David  35.0         IT  62000.0         62500.0  High
4           4      Eve  29.0         HR  50000.0         50500.0   Low
5           5    Alice  25.0         HR  50000.0         50500.0   Low

In [155]:
datas.groupby("Department")["Salary"].mean()

Department
Finance    70000.0
HR         50000.0
IT         61000.0
Name: Salary, dtype: float64